// @askverdict/sdk — TypeScript API client for AskVerdict
// Published as: @askverdict/sdk

export { AskVerdictClient } from "./client.js";

export {
  AskVerdictError,
  type AskVerdictClientConfig,
  type CreateDebateParams,
  type CreateDebateResult,
  type DebateMode,
  type DebateStatus,
  type DebateResponse,
  type ListDebatesParams,
  type ListDebatesResult,
  type VoteValue,
  type VoteMap,
  type ClaimVoteTally,
  type PollOption,
  type Poll,
  type HealthResponse,
  type StreamEvent,
  type SdkError,
  type Verdict,
  type DebateCostRecord,
  type FundingSource,
  type UserProfile,
  type UsageInfo,
  type BalanceInfo,
  type CheckoutPlan,
  type CheckoutInterval,
  type CreditPack,
  type CheckoutUrlResult,
  type PortalUrlResult,
  type DashboardStats,
  type SearchParams,
  type SearchResultItem,
  type SearchResult,
  type OutcomeRecord,
  type SubmitOutcomeParams,
  type DecisionScore,
  type StreakInfo,
  type ApiKeyUsage,
} from "./types.js";
